version: '2'
services:
  data-volumes:
    image: 'debian:jessie'
    volumes:
      - ./mnt:/mnt
      - /var/www
      - /var/lib/mysql
      - /var/lib/letsencrypt
      - /etc/letsencrypt
      - /znc-data
      - /teamspeak3
  data-backup:
    build: 'data-backup'
    volumes_from:
      - data-volumes
    restart: always
  data-restore:
    build: 'data-restore'
    volumes_from:
      - data-volumes
  web-hhvm:
    build: 'web-hhvm'
    volumes_from:
      - data-volumes
    restart: always
  web-nginx:
    build: 'web-nginx'
    volumes_from:
      - data-volumes
    ports:
      - '80:80'
      - '443:443'
    restart: always
  web-mariadb:
    image: 'mariadb'
    volumes_from:
      - data-volumes
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
  web-scgf:
    image: 'rdkr/steam-common-game-finder'
    restart: always
    environment:
      - STEAM_WEB_API_KEY=<api key - no quotes>
  web-letsencrypt:
    build: 'web-letsencrypt'
    volumes_from:
      - data-volumes
  teamspeak:
    image: 'luzifer/teamspeak3'
    ports:
     - "9987:9987/udp"
     - "30033:30033"
     - "10011:10011"
    volumes_from:
     - data-volumes
    restart: always
  znc:
    image: 'jimeh/znc'
    ports:
      - '6667:6667'
    volumes_from:
      - data-volumes
    restart: always
