web-data:
  build: 'web-data'
  volumes_from:
    - web-volumes
  volumes:
    - './mnt:/mnt'
  links:
    - web-mariadb

web-volumes:
  image: 'debian:jessie'
  volumes:
    - /var/www
    - /etc/nginx/common
    - /etc/nginx/conf.d
    - /var/lib/mysql

web-hhvm:
  image: 'diegomarangoni/hhvm:fastcgi'
  volumes_from:
    - web-volumes
  links:
    - web-mariadb

web-nginx:
  build: 'web-nginx'
  volumes_from:
    - web-volumes  
  links:
    - web-hhvm
  ports:
    - '80:80'

web-mariadb:
  image: 'mariadb'
  volumes_from:
    - web-volumes
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes